styled-components/stylelint-processor-styled-components

- README.md
Using single quotes in the stylelint command didn't work for me (PC, Stylelint 7.7.1). This stackoverflow page simply suggested replacing single quotes with double: http://stackoverflow.com/questions/38814200/files-glob-patterns-specified-did-not-match-any-files - this fixed it for me. Checking out the stylelint docs I didn't see any reference to this issue but all examples used double quotes, so this should be safe.
> syntax update for stylelint npm scripts cmd

- test/fixtures/interpolations/complex.js
- test/interpolations.test.js
This adds failing tests for complex interpolations of chunks. The rules are based on the official examples  on [this page](https://github.com/styled-components/styled-components/blob/master/docs/tagged-template-literals.md#in-styled-components).
See issue #6
> Add failing tests for complex interpolations

- src/utils/general.js
- src/utils/tagged-template-literal.js
- test/fixtures/interpolations/complex.js
- test/interpolations.test.js
- test/utils.test.js
Merged tests from #8 and fixed #6. This change complicates `interleave` function and also introduces *vendor prefixed* property `-styled-mixin`.
```js
const Button = styled.button`
color: blue;
${additionalButtonStyles}
`
```
Is now transformed to:
```css
.selector {
color: blue;
-styled-mixin: additionalButtonStyles;
}
```
> Fixed complex interpolations

- README.md
In the scripts, it works if using single quotes as well. This should improve the readability.
> Docs: change quotes for better reading

- src/index.js
Closes #22
BTW, i would recommend don't changed `stylelintResult`, just add node in `README.md` about disable `no-empty-source` and `no-missing-end-of-source-newline`, in next version we can change `stylelintResult` (example rename `warnings` to another name) and `stylelint-processor-styled-components` will cease to work as expected.
> Fixed: set `errored` to `false` if `warning` no contains errors.

- .gitignore
- package.json
- src/index.js
- src/parsers/babylon-parser.js
- src/parsers/index.js
- src/parsers/typescript-parser.js
- test/fixtures/typescript/ts-syntax-invalid.ts
- test/fixtures/typescript/ts-syntax-jsx-invalid.tsx
- test/fixtures/typescript/ts-syntax-no-styled-components.tsx
- test/fixtures/typescript/ts-syntax-valid.ts
- test/typescript.test.js
Add support for .ts, .tsx parsing and reporting.
A small refactor to allow integration of new parser cleanly
A few tests demonstrating parsing and error reporting in both .ts and .tsx files
> Add support for Typescript files. Closes #12

- package-lock.json
- package.json
See #32. This pr fixes having to install typescript manually (typescript-eslint-parser requires it as a peerdependency). However it does mean that there's no more freedom for the user to choose which exact version they want to use. But since typescript-eslint-parser has a specific dependency range (currently `~2.3.2`) the choice is limited anyway.
Closes #32
> Move typescript to dependencies

- README.md
I was trying to think of a better example for a rule to break, but as I'm new to stylelint I couldn't find a good one yet, if anyone has a better example feel free to suggest that.
Especially using the media queries (though it is an example in the docs) could be a bit confusing I guess, but yeah, as I'm new to stylelint it was just hard to think of good examples.
It'd be neat to have in here though so no one else submits erroneous issues like I did :).
> Add stylelint-disable note in README.md

- src/utils/general.js
- src/utils/tagged-template-literal.js
- test/fixtures/interpolations/valid.js
- test/utils.test.js
related to #20 #21
This change enable to use multiple interpolations in a property at once.
```
width: 20px;
border: ${borderWidth} ${borderStyle} ${color};
```
is now translated to:
```
width: 20px;
border: $borderWidth -styled-mixin: borderStyle; -styled-mixin: color;
```
This changes above to: 
```
width: 20px;
border: $borderWidth $borderStyle $color;
```
Cc: @mxstbr
> Fixed multiple interpolations in a property

- README.md
I guess it was just a silly mistake when linking up coveralls while being on the wrong branch
> README Coveralls url was erroneously linking to a branch called ci

- README.md
- src/utils/tagged-template-literal.js
- test/fixtures/interpolations/valid.js
- test/interpolations.test.js
- test/utils.test.js
Up until now I just added a failing test for #55. It seems to be a problem with [this line](https://github.com/styled-components/stylelint-processor-styled-components/blob/3c43e97f5678ece590cd6a284b0e943fc69073af/src/utils/tagged-template-literal.js#L21) returning undefined on a string as opposed to a variable.
I'll probably look at it again tomorrow night after work, and see if I can also fix it, my first impression is that it's a bigger problem with the approach and that it's better to find a better approach rather than patching an edge case for another one to soon pop out, but again, I haven't looked at it that much yet.
Any advice from more seasoned contributors that know the codebase better is of course welcome, otherwise I'll look at it again tomorrow night.
(fixes #55)
> Make -styled-mixins unique and clarify interpolation linting in readme

- src/utils/general.js
- src/utils/tagged-template-literal.js
- test/fixtures/interpolations/valid.js
- test/utils.test.js
I found a few edge cases, and while working on #59 I also just saw that tests for `interleave` were a bit lacking, so I felt like adding a few tests there that weren't braking but just for good form as well. I might have some more edge cases in mind as well. This is WIP but will resolve #62 and is related to #52.
It is branched off from #59 at the moment so until that is merged the diff here is a bit overkill.
> Beef up interpolation tests and interleave function to handle more edge cases

- README.md
- src/utils/general.js
- test/fixtures/hard/indentation.js
- test/fixtures/hard/invalid-indentation.js
- test/hard.test.js
- test/utils.test.js
This resolves #51.
Problem was that when replacing empty lines we were assuming base indentation was always 2 spaces, so in the min function it would always find 2 as the minimum if base indentation was actually more.
I changed it to assuming that the last backtick of the TTL is put on the level of the "base indentation level" which I think is a quite fair assumption, any better ideas?
Also will just put a comment in the code in one place when I submit the PR for something I was curious about.
I think it could probably be merged in now, could be I put in a few more tests tomorrow for oneline stuff etc. ? and more specifically for the issue that was found to be the root instead of just the specific case submitted in the issue.
> Fix indented TTL case

- README.md
I think my Webpack loader is ready to see the light with core features etc. at least. I'd love to add it to the README here in a combination of shameless promotion of my own npm module and also just because I know I really wanted this when I started using our processor.
P.S: I stole your good idea of the gif in the README but upgraded it with the hot reloading webpack allows ;).
> Add reference to stylelint-custom-processor-loader to README

- package-lock.json
- package.json
- src/parsers/index.js
I found a solution :). As long as you guys are okay with conditional requires. This resolves #99
> Move typescript to devDependencies

- src/parsers/index.js
- src/utils/styled.js
- test/fixtures/simple/identify-styled.js
- test/simple.test.js
I have currently implemented a fix for #106 (`.attrs`) but after double checking the Styled Components API I also want to put in a similar check for `.extend` before merging it in.
EDIT:
Done, this should add support for both `.extend` and `.attrs`, and is ready for review now.
resolves #106
> Support Styled Component properties

- package.json
Updated Greenkeeper Ignore to not update any of our devDependencies that aren't directly related to the performance of the repo. (also removed Typescript from the ignore as I guess it could potentially be important to track the changes of that for our Typescript support, yes?)
This would also close #120
> Update Greenkeeper Ignore

- .babelrc
- .travis.yml
- package-lock.json
- package.json
- test/hard.test.js
- test/ignore-rule-comments.test.js
- test/inject-global.test.js
- test/interpolation-tagging.test.js
- test/interpolations.test.js
- test/options.test.js
- test/real-world.test.js
- test/simple.test.js
- test/typescript.test.js
- test/utils.test.js
Fixes #136.
Without `.babelrc`, the current build script can't transform any codes at all. Node 4 doesn't support those new ES6 syntaxes, so errors were thrown.
> Add .babelrc

- package-lock.json
- package.json
- src/index.js
- src/utils/general.js
- src/utils/tagged-template-literal.js
- test/interpolation-tagging.test.js
- test/utils.test.js
Fixes #131 
stylelint throws any error not related to "CssSyntaxError"
https://github.com/stylelint/stylelint/blob/ded86c81d055b3916ef3242a390fd7dad00ca8a7/lib/standalone.js#L277
Changes:
1. Ignore any parsing errors from babylon
2. Throw CssSyntaxError for wrong interpolation tags (previously was just Error) so stylelint can eat & handle them
> Ignore parsing errors, fix #131

- src/index.js
This will catch errors when filepath is undefined.
Happens when viewing diff from git tab in vscode.
> Wrap whole transform block in try/catch

- src/index.js
- test/nofiles.test.js
Fixes #76. The input id matches [the logic of postcss](https://github.com/postcss/postcss/blob/master/lib/input.es6#L78).
Please notice that current `package-lock.json` uses `stylelint@8.0.0`, which doesn't validate the existence of `codeFilename`. But from [8.1.0](https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#810), non-existed `codeFilename` will also cause `filepath` to be undefined. If you want to upgrade `stylelint`, my second commit can be reverted.
> Fix if no file name given

- package-lock.json
- package.json
- test/jest-setup.js
I was just getting sick of all the failed Travis builds which were mostly due to timeouts when doing the coverage which I guess makes the tests take that little longer that makes the tests time out on the relatively slow CI CPU, so added this.
I guess this should just be mergeable, but for good measure if @mxstbr or @ismay could just approve it?
> Increase async test timeout

- test/fixtures/hard/valid-js-comments.js
- test/hard.test.js
Test cases for JS style line comments, this should close #156 either by adding the functionality if we find out it is actually broken or just by merging this PR with the passing tests that properly document that we support this
> Add test cases for line comments

- README.md
A minor doc change that swaps [stylelint-config-recommend](https://github.com/stylelint/stylelint-config-recommended) in for [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard).  I suspect this config will be more useful to the majority of the users of this processor at it works well with pretty-printers like Prettier. Whereas, the _stylistic_ rules in stylelint-config-standard can sometimes conflict with them.
Incidentally, I believe this could make the lack of `--fix` support in processors less of a limitation as the majority of non-stylistic rules can't be automatically fixed e.g. rules that:
- [check CSS code for mistakes](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#possible-errors) and surface bugs earlier (e.g. …
> Use stylelint-config-recommend in examples

- src/utils/general.js
- test/fixtures/interpolations/valid.js
- test/utils.test.js
The previous PR #84 fixed comments before interpolations but does not work for multiline comments.
The updated RegEx will now match any characters that are not `*/` (https://regexr.com/3m0r1).
```css
/* single line */
display: block;
/* 
multiline with "*" and "/"
*/
display: block;
/** 
* JsDoc style
*/
display: block;
```
> Fixed interpolations following a multiline comment

- .babelrc
- .travis.yml
Usually, `npm` is installed with `nodejs`. And latest npm@6.1.0 is not compatible with nodejs@4, which will break our CI.
> Remove extra npm install

- src/parsers/babylon-parser.js
As discussed in #183 this will be the first quick fix with adding `optionalChainging` to the plugin list.
> Add 'optionalChaining' to babylon-parser

- test/hard.test.js
Be careful. Without corresponding rules set, the test will be always passed.
> Fix JS style comments are not tested

- README.md
This usage should be `your` instead of `you're`
> fix "you're" typo in readme

- src/index.js
- src/parsers/index.js
- test/fixtures/options/import-name.js
- test/fixtures/options/invalid-import-name.js
- test/options.test.js
Hi!
this PR allows the user to override the import name (currently it's set to "default"). 
In our project we have a file that re-exports Styled with type parameters. The problem is that we use a named export instead of a default export.
> allow overriding import name

- src/index.js
- test/emptycode.test.js
> Keep the original line number if no source map

- src/index.js
When used with vscode-stylelint extension, the entire module will be loaded and kept in memory, thus sharing state between various validate requests. The problem comes when file had parsing error (due incorrect syntax or incomplete statements - vscode sends validate request while you're typing something) it will store parse error into ```errorWasThrown``` shared object. Since the module is preserved in memory, subsequent runs will return this error due to this line https://github.com/styled-components/stylelint-processor-styled-components/blob/d055954273328a2fb11b48d5b48533b2afdadce7/src/index.js#L69 even for perfectly valid file.
> Clean parse error on success parsing

- src/index.js
- src/parsers/index.js
- src/utils/result.js
- test/fixtures/hard/source-maps.js
- test/hard.test.js
- test/utils.test.js
Fixes #232.
Notice that this PR don't consider multiple tagged literals in the same line, or the tagged literal starts with an interpolation. Because in current code structure, it is hard to determine where the lint warning comes from and what an interpolation will be converted to.
> Fix the column number if it is at the first line of interpolation

- src/index.js
- src/parsers/index.js
- test/fixtures/options/strict.js
- test/options.test.js
Fixes #253.
Enables stricter parsing, in that only expressions using the specified
`importName` from the `moduleName` will be parsed.
```ts
// moduleName = some-module, importName = foo
import { foo, bar } from 'some-module';
foo`test`; // parsed
bar`test`; // parsed
foo.bleh`test`; // parsed
bar.bleh`test`; // parsed
// moduleName = some-module, importName = foo, strict = true
import { foo, bar } from 'some-module';
foo`test`; // parsed
bar`test`; // ignored
foo.bleh`test`; // parsed
bar.bleh`test`; // ignored
```
> add `strict` option

- package-lock.json
- package.json
- src/index.js
Adding option `ignoreFiles` to filter file types.
In my case this way I can filter `*.css` files to use the processor only in `js, jsx` files.
Solves #187.
> Add option ignoreFiles to filter fileTypes

- README.md
> Add docs for options and fix something

- README.md
At least in my bash shell when copy pasting the `npm install ...` it's running a full install and complains that all the libs are no bash commands.
> Readme: Setup allow copy paste of npm install
